[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-ffi"
version = "0.3.0"
description = "Shared library for the Segments Filter engine FFI"
publish = false

[package.metadata.deb]
assets = [["target/release/libwirefilter_ffi.so", "usr/local/lib/libwirefilter.so", "644"]]

[lib]
crate-type = ["cdylib"]
# Avoid duplicate compilation error messages as we don't have doctests anyway
doctest = false

[dependencies]
fnv = "1.0.6"
libc = "0.2.42"
serde_json = "1.0.27"

[dependencies.wirefilter-engine]
path = "../engine"

[dev-dependencies]
regex = "1.0.1"
indoc = "0.2.6"
