[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-ffi"
version = "0.2.2"
description = "Shared library for the Segments Filter engine FFI"
publish = false

[dependencies]
fnv = "1.0.6"
libc = "0.2.42"

[dev-dependencies]
regex = "1.0.1"

[dependencies.wirefilter-engine]
path = "../engine"

[lib]
crate-type = ["cdylib"]
name = "wirefilter"

[package.metadata.deb]
assets = [["target/release/libwirefilter.so", "usr/local/lib/", "644"]]
