[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-ffi"
version = "0.1.0"

[dependencies]
libc = "0.2.36"

[dependencies.wirefilter-engine]
path = "../engine"

[lib]
crate-type = ["cdylib"]
name = "wirefilter"
