[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-ffi"
version = "0.1.0"
description = "Shared library for the Segments Filter engine FFI"
publish = false

[dependencies]
libc = "0.2.36"

[dependencies.wirefilter-engine]
path = "../engine"

[lib]
crate-type = ["cdylib"]
name = "wirefilter"

[package.metadata.deb]
assets = [["target/release/libwirefilter.so", "usr/local/lib/", "644"]]
