[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter"
version = "0.1.0"

[dependencies]
cidr = "0.0.3"
failure = "0.1.1"
fnv = "1.0.6"
ordermap = "0.3.5"
regex = "0.2.5"
serde = "1.0.27"
serde_bytes = "0.10.3"
serde_derive = "1.0.27"

[dev-dependencies]
bincode = "0.9.2"
serde_cbor = "0.8.1"
serde_json = "1.0.9"

[workspace]
