[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-engine"
version = "0.4.1"
description = "Rust library for the Segments Filter engine"
publish = false

[lib]
name = "wirefilter"
# Avoid duplicate compilation error messages as we don't have doctests anyway
doctest = false

[[bench]]
name = "bench"
harness = false

[dependencies]
cidr = { version = "0.0.4", default-features = false }
failure = "0.1.1"
fnv = "1.0.6"
indexmap = { version = "1.0.1", features = ["serde-1"] }
regex = "1.0.1"
memmem = "0.1.1"
serde = { version = "1.0.78", features = ["derive"] }

[dev-dependencies]
indoc = "0.2.6"
criterion = "0.2.5"
serde_json = "1.0.27"
