[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-engine"
version = "0.1.0"
description = "Rust library for the Segments Filter engine"
publish = false

[dependencies]
cidr = { version = "0.0.4", default-features = false }
failure = "0.1.1"
fnv = "1.0.6"
ordermap = "0.3.5"
regex = "0.2.5"

[lib]
name = "wirefilter"
